sonar.projectKey=rekyb-1893_marka-editor
sonar.organization=rekyb-1893
sonar.projectName=Marka Editor
sonar.projectVersion=0.1.0

sonar.sources=src
sonar.exclusions=**/*.test.ts,**/*.test.tsx,node_modules/**,coverage/**,dist/**,.next/**
sonar.sourceEncoding=UTF-8

sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.javascript.file.suffixes=.js,.jsx,.ts,.tsx
sonar.typescript.file.suffixes=.ts,.tsx

sonar.coverage.exclusions=**/*.test.ts,**/*.test.tsx,src/types/**,src/constants/**
